CREATE USER C##KSUSHA IDENTIFIED BY K2510k2510;

GRANT CONNECT, RESOURCE TO C##KSUSHA;
GRANT CREATE TABLE TO C##KSUSHA;
GRANT CREATE SEQUENCE TO C##KSUSHA;
GRANT CREATE TRIGGER TO C##KSUSHA;

GRANT CREATE SESSION TO C##KSUSHA;

GRANT CONNECT, RESOURCE TO C##KSUSHA;
GRANT CREATE VIEW TO C##KSUSHA;
GRANT CREATE SYNONYM TO C##KSUSHA;

GRANT EXECUTE ON SYS.DBMS_OUTPUT TO C##KSUSHA;
ALTER USER C##KSUSHA QUOTA UNLIMITED ON USERS;

CREATE OR REPLACE DIRECTORY dir AS 'C:\Users\lishy\OneDrive\Documents\sybd2\Lab5';
CREATE OR REPLACE DIRECTORY DIR AS 'C:\oracle_reports';
GRANT WRITE ON DIRECTORY dir TO C##KSUSHA;
GRANT READ, WRITE ON DIRECTORY dir TO C##KSUSHA;

CREATE OR REPLACE DIRECTORY reports_dir AS 'C:\oracle_reports';
GRANT READ, WRITE ON DIRECTORY reports_dir TO C##KSUSHA;
SELECT * FROM ALL_DIRECTORIES WHERE DIRECTORY_NAME = 'REPORTS_DIR';
SELECT * FROM ALL_TAB_PRIVS WHERE TABLE_NAME = 'REPORTS_DIR' AND GRANTEE = 'C##KSUSHA';
SELECT * FROM ALL_DIRECTORIES;
