export enum AUTH_ERROR {
  INCORRECT_PASSWORD = 'INCORRECT_PASSWORD',
  INCORRECT_REFRESH_TOKEN = 'INCORRECT_REFRESH_TOKEN',
  INVALID_EMAIL = 'INVALID_EMAIL',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
}
