version: '3.8'

services:
  postgres:
    image: postgres:14.8
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
